stages:
  run_notebook:
    cmd: papermill TrainChurnModel.ipynb TrainChurnModel_out.ipynb
    deps:
      - data/Churn_Modelling.csv
      - TrainChurnModel.ipynb
    params:
      - base
      - data_split
      - train
    outs:
      - models/model.joblib
    metrics:
      - metrics.json:
          cache: false
    plots:
      - eval_plots/cm.png:
          cache: false
      - eval_plots/plots/roc.json:
          cache: false
          x: fpr
          y: tpr